include:
  - board: nice_nano_v2
    # shield: corax_left nice_view
    shield: settings_reset
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano_v2
  #   shield: corax_right nice_view
    #- board: nice_nano_v2
    #shield: settings_reset
